### ISSUE TITLE
Issue Created for reviewer

### ISSUE THREAD

**Issue by shahzaman900** [sheezu900/javascript-capston-project#21]
### Issue Created for reviewer

**2 Group Partners**

1. Shah Zaman
2. Fatima Najafi

[javascript capston project](https://github.com/sheezu900/javascript-capston-project/projects/1)

**Comment by julie-ify** [comment]
Hi @sheezu900 and @fatima-najafi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* You provided the link to your repo, instead of the Kanban project. Kindly fix that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by iambenkis** [comment]
## Project Approved ✅ 

Hi @sheezu900 , @julie-ify ,

Everything is looking great! You can now start the project!!! :shipit:
Congratulations! 🎉


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
